### ISSUE TITLE
Svelte formatting

### ISSUE THREAD

**Issue by jgero** [lspcontainers/dockerfiles#41]
With the current docker image formatting does not work for me. But in the [docs of the svelte-language-server](https://www.npmjs.com/package/svelte-language-server) it says that it supports formatting via prettier. I tried installing prettier and prettier-plugin-svelte in the container as well but still no success. Would it be possible to make formatting work with the lspcontainers or do I have to make that work another way?

**Comment by jgero** [comment]
Updating the language server to 0.14.3 solved it for me, I already created #42 for it.

**Comment by erkrnt** [comment]
Merged 👍
