### ISSUE TITLE
bashls crashes after a short while

### ISSUE THREAD

**Issue by WhyNotHugo** [lspcontainers/dockerfiles#53]
`bashls` crashes after a short while.

I noticed the Dockerfile doesn't install `bash`,  so I tried adding that: 

```diff
diff --git a/servers/bashls/Dockerfile b/servers/bashls/Dockerfile
index 4a528f1..89f44f8 100644
--- a/servers/bashls/Dockerfile
+++ b/servers/bashls/Dockerfile
@@ -2,7 +2,8 @@ FROM alpine:3.13.5

 RUN apk add --no-cache \
   nodejs \
-  npm
+  npm \
+  bash

 ARG VERSION
```

I also tried updating to the latest version, but that didn't fix it either:

Here's my very simple `test.bash`:

```bash
#!/usr/bin/bash

echo $*
```

All I can see is that it exits 1. The container's logs don't yield any clues either.

**Comment by WhyNotHugo** [comment]
Gathering info to ask upstream:

```
➜  podman logs 41bdc26368f3
Content-Length: 121

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Initialized server v. 1.17.0 for undefined"}}Content-Length: 316
```

**Comment by WhyNotHugo** [comment]
This seems to be the same as https://github.com/johnsoncodehk/volar/issues/706

Apparently `podman` (or `docker`) needs to be passed a `--pid=host` argument. I'll figure out how to make this configurable on a per-LSP basis, and push a PR.

**Comment by erikreinert** [comment]
Is this still an issue? I believe we solved the PID problem in other locations - so we should be able to solve it here if we haven't already.

**Comment by WhyNotHugo** [comment]
It's fixed; it was the PID issue.
