### ISSUE TITLE
Add nightly job

### ISSUE THREAD

**Issue by erikreinert** [lspcontainers/dockerfiles#69]
Now that we use `latest` for everything - we want to start building our LSPs nightly to provide our users with the latest and greatest.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by jgero** [comment]
Wouldn't it suffice to run the build and publish just on every merge to main?

**Comment by erikreinert** [comment]
We already do this - this would be to rotate images nightly so we also get those updates too.
